package com.yugesh.dsa.problems.algorithm._2_frequencyMap.easy.leetcode;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class FrequencyMap_2 {

    public static void main(String[] args) {

        int[]nums1={4,9,5};
        int[]nums2={9,4,9,8,4};
        System.out.println(intersectionOfArrays(nums1,nums2));

        int[]num3={4,9,5};
        int[]num4={9,4,9,8,4};
        System.out.println(intersectionOfArray(num3,num4));

        String pattern="abba";
        String word="dog dog dog dog";
        System.out.println(wordPattern(pattern,word));

         String s="aab";
        String t="abaa";
        System.out.println(findDifferenceInCharacter(s,t));

         System.out.println(SingleNumber(new int[]{4,1,2,1,2}));
    }

    /**
     * 🧩 Problem 9 — Intersection of Two Arrays
     * Source: LeetCode
     * 📌 Problem Statement (clean)
     * You are given two integer arrays nums1 and nums2.
     * Return an array of their intersection.
     * Each element in the result must be unique, and you may return the result in any order.
     * @param num1
     * @param num2
     * @return
     */
    public static List<Integer> intersectionOfArrays(int[]num1,int[] num2){
        Set<Integer>set=new HashSet<>();
        Set<Integer>sets=new HashSet<>();

        for(int i:num1){
            set.add(i);
        }
        for(int i:num2){
            if(set.contains(i)){
                sets.add(i);
            }
        }
        return new ArrayList<>(sets);
    }

     /**
     * 🧩 Problem 10 — Intersection of Two Arrays II
     * Source: LeetCode
     * 📌 Problem Statement (clean)
     * You are given two integer arrays nums1 and nums2.
     * Return an array of their intersection.
     * Each element in the result should appear as many times as it shows in both arrays.
     * You may return the result in any order.
     * @param num1
     * @param num2
     * @return
     */
    public static List<Integer> intersectionOfArray(int[]num1,int[]num2){
        Map<Integer,Integer>map1=new HashMap<>();
        Map<Integer,Integer>map2=new HashMap<>();
        List<Integer>list=new ArrayList<>();

        for(int i:num1){
            map1.put(i,map1.getOrDefault(i,0)+1);
        }
        for(int i:num2){
            map2.put(i,map2.getOrDefault(i,0)+1);
        }

        for(Map.Entry<Integer,Integer>m:map1.entrySet()){
            int key=m.getKey();
            if(map2.containsKey(key)){
                    int count=Math.min(m.getValue(),map2.get(key));
                    while (count>0){
                        list.add(key);
                        count--;
                    }

            }
        }
        return list;
    }

     /**
     * 🧩 Problem 11 — Word Pattern
     * Source: LeetCode
     * 📌 Problem Statement (clean)
     * You are given:
     * a string pattern
     * a string s (space-separated words)
     * Return true if s follows the same pattern.
     * Rules:
     * Each character in pattern maps to exactly one word
     * Each word maps to exactly one character
     * Mapping must be bijective (one-to-one)
     * pattern = "abba", s = "dog cat cat dog"   → true
     * pattern = "abba", s = "dog cat cat fish" → false
     * pattern = "aaaa", s = "dog cat cat dog"  → false
     * pattern = "abba", s = "dog dog dog dog"  → false
     * @param pattern
     * @param word
     * @return
     */
    public static boolean wordPattern(String pattern, String word){

       String[]words=word.split(" ");
       if(pattern.length()!=words.length){
           return false;
        }
       Map<Character,String>charToWord=new HashMap<>();
       Map<String,Character>wordToChar=new HashMap<>();

       for(int i=0;i<words.length;i++){
           char c=pattern.charAt(i);
           String w=words[i];

           if(charToWord.containsKey(c)){
               if(!charToWord.get(c).equals(w)){
                   return false;
               }
           }else {
               charToWord.put(c,w);
           }

           if(wordToChar.containsKey(w)){
               if(wordToChar.get(w)!=c){
                   return false;
               }
           }else {
               wordToChar.put(w,c);
           }
       }
       return true;
    }

        /**
     * 🧩 Problem 12 — Find the Difference
     * Source: LeetCode
     * 📌 Problem Statement (clean)
     * You are given two strings:
     * s
     * t
     * t is generated by shuffling the characters of s and adding exactly one extra character.
     * Return the extra character.
     * @param s
     * @param t
     * @return
     */
    public static char findDifferenceInCharacter(String s,String t){
       Map<Character,Integer>map=new HashMap<>();

       for(char ss:s.toCharArray()){
           map.put(ss,map.getOrDefault(ss,0)+1);
       }

       for(char tt:t.toCharArray()){
           if(!map.containsKey(tt)||map.get(tt)==0){
               return tt;
           }
           map.put(tt,map.get(tt)-1);
       }
       return ' ';
    }

     public static int SingleNumber(int[]n){
       Map<Integer,Integer>map=new HashMap<>();

       for(int i:n){
         map.put(i,map.getOrDefault(i,0)+1);
       }
       for(Map.Entry<Integer,Integer>m:map.entrySet()){
           if(m.getValue()==1){
               return m.getKey();
           }
       }
       return -1;
    }
//    public static int SingleNumber(int[]n){
//        int result=-1;
//        for(int i:n){
//            result^=i;
//        }
//        return result;
//    }
}
